spring:
  datasource:
    username: root
    password: 1115
    url: jdbc:mariadb://localhost:3306/coupon?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: off